//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Istorie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public int clasaId { get; set; }
        public string name { get; set; }
        public int uniqueCode { get; set; }
        public string descriere { get; set; }
        public int userId { get; set; }
    
        public virtual User User { get; set; }

        


    }
}
